# Generated by Django 4.2 on 2024-06-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('view_any_mailing', 'Can view any mailing'), ('disable_mailing', 'Can disable mailings'), ('block_user', 'Can block users'), ('allow_mailing', 'Can allow mailings')], 'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
    ]
